### ISSUE TITLE
Cannot read Contact Object in MS-Graph-Data-Connect

### ISSUE THREAD

**Issue by Asha-Khubani** [OfficeDev/MS-Graph-Data-Connect#61]
Hello I am trying to read data from contact object and to store in azure blob storage through azure factory pipeline  but I am getting below error:

{ "errorCode": "2200", "message": "ErrorCode=UserErrorOffice365DataLoaderError,'Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Office365 data loading failed to execute. Group Expansion Failed. Please contact us for support.,Source=Microsoft.DataTransfer.ClientLibrary,'", "failureType": "UserError", "target": "Copy Data1" }

I am able to read emails and events successfully. Can somebody help me why I am getting this issue?

**Comment by tlenig** [comment]
Thank you for reaching out Asha! This error is likely due to the fact that you do not have sufficient licenses assigned to the users you are requesting data for. To utilize the Microsoft Graph data connect, the users you are requesting data for must have both a valid Exchange license and a Workplace Analytics license. For more details on the licensing story (including how to obtain a Workplace Analytics license) visit our documentation on licensing: https://docs.microsoft.com/en-us/graph/data-connect-policies#licensing

**Comment by Asha-Khubani** [comment]
Thank you for your quick response. But we have a doubt it is due to license  because

1) Getting mail worked with same users before few days but now its not working too
2) Getting events worked with same users before few days but now its not working too
3) Getting contacts never worked got "Group expansion failed" error

Can you please explain why mails and events worked with same users before?

**Comment by tlenig** [comment]
No problem! This likely occurred because your pipelines for mails/events happened before the license check was enforced, while the contacts pull happened only after the license check was enforced. Moving forward, the license will be required, thus you will see an error using data connect in your organization for any data type if none of the users requested have a Workplace Analytics license.
